// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfodyeejtmazwhhwtafh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mb2R5ZWVqdG1hendoaHd0YWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzkyNjUsImV4cCI6MjA2NTY1NTI2NX0.FmUAFZvgRONArWDB9FWQiZOLJ9OFc1Wd762rU01i68M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);